database:
  CCP_IMAGE_TAG:  centos7-9.6-1.2.8
  Port:  5432
  PVC_NAME:  crunchy-pvc
  PG_MASTER_USER:  master
  PG_MASTER_PASSWORD:  password
  PG_USER:  testuser
  PG_PASSWORD:  password
  PG_DATABASE:  userdb
  PG_ROOT_PASSWORD:  password
cluster:
  CCP_IMAGE_TAG:  centos7-9.6-1.2.8
  Port:  5432
  PVC_NAME:  crunchy-pvc
  PG_MASTER_USER:  master
  PG_MASTER_PASSWORD:  password
  PG_USER:  testuser
  PG_PASSWORD:  password
  PG_DATABASE:  userdb
  PG_ROOT_PASSWORD:  password
  REPLICAS:  2
